name: .NET CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Ecommercedb

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3306;Database=Ecommercedb;User=root;Password=;"

      Jwt__Key: "CI_TEST_JWT_SECRET_KEY_12345678901234567890123456789012345678901234567890"
      Jwt__Issuer: "ECommerceAPI"
      Jwt__Audience: "ECommerceClient"

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ECommerceSolution.slnx

      - name: Build solution
        run: dotnet build ECommerceSolution.slnx --configuration Release --no-restore

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root -proot --silent; then
              echo "MySQL is ready."
              break
            fi

            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run EF migrations
        run: |
          dotnet ef database update \
            --project ECommerce.Infrastructure \
            --startup-project ECommerce.API

      - name: Run tests
        run: dotnet test ECommerceSolution.slnx --configuration Release --no-build